#!/bin/sh
# chkconfig:         2345 95 05
# description:       Pyswitchlib api daemon is an object broker for pyswitchlib assets.
### BEGIN INIT INFO
# Provides:          pyswitchlib api daemon
# Required-Start:    $local_fs $network $remote_fs $syslog
# Required-Stop:     $local_fs $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Pyswitchlib api broker
# Description:       Pyswitchlib api daemon is an object broker for pyswitchlib assets.
#
### END INIT INFO

# Author: Brian Adaniya <badaniya@brocade.com>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="pyswitchlib-api-daemon"
NAME=pyswitchlib-api-daemon
SCRIPTNAME=/etc/init.d/$NAME
VIRTENV_PATH="/opt/stackstorm/virtualenvs"
PYSWITCHLIB_PATH="/lib/python2.7/site-packages/pyswitchlib"
PACKNAME="dcfabric"
PACKNAME2="network_essentials"
FILENAME="pyswitchlib_api_daemon.py"
PYSWITCHLIB_DAEMON_PATH=""
VIRTENV_PACK_PATH=""

if [ -e "$VIRTENV_PATH/$PACKNAME$PYSWITCHLIB_PATH/$FILENAME" ]; then
    PYSWITCHLIB_DAEMON_PATH="$VIRTENV_PATH/$PACKNAME$PYSWITCHLIB_PATH/$FILENAME"
    VIRTENV_PACK_PATH="$VIRTENV_PATH/$PACKNAME"
elif [ -e "$VIRTENV_PATH/$PACKNAME2/$PYSWITCHLIB_PATH/$FILENAME" ]; then
    PYSWITCHLIB_DAEMON_PATH="$VIRTENV_PATH/$PACKNAME2$PYSWITCHLIB_PATH/$FILENAME"
    VIRTENV_PACK_PATH="$VIRTENV_PATH/$PACKNAME2"
else
    PYSWITCHLIB_DAEMON_PATH="`python -c \"import os; import sys; print(sorted(os.path.join(x, 'pyswitchlib') for x in sys.path if os.path.isdir(os.path.join(x, 'pyswitchlib')))[0])\"`/$FILENAME"
    VIRTENV_PACK_PATH=""
fi

pyswitchlib_api_daemon_wrapper()
{
    local OPERATION="$1"
    local RETVAL=0

    if [ -n "$PYSWITCHLIB_DAEMON_PATH" ]; then
        if [ -n "$VIRTENV_PACK_PATH" ]; then
            . "$VIRTENV_PACK_PATH/bin/activate"
        fi
        
        if [ "$OPERATION" == "start" || "$OPERATION" == "restart" ]; then
            (python "$PYSWITCHLIB_DAEMON_PATH" "$OPERATION" &)
        else:
            python "$PYSWITCHLIB_DAEMON_PATH" "$OPERATION"

        RETVAL="$?"
    fi

    return "$RETVAL"
}

case "$1" in
    start|stop|restart|status)
    pyswitchlib_api_daemon_wrapper "$1"
    exit $?
    ;;
    *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
    exit 3
    ;;
esac
